/**
 * Licensed to Apereo under one or more contributor license
 * agreements. See the NOTICE file distributed with this work
 * for additional information regarding copyright ownership.
 * Apereo licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a
 * copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package scripteditor;

import java.awt.Dialog;

/**
 *
 * @author tbisciglia
 */
public class DiffDialog extends javax.swing.JDialog {

    /**
     * Creates new form DiffDialog
     */
    public DiffDialog(Dialog parent, boolean modal, String message) {
        super(parent, modal);
        initComponents();
        diffMessage.setText(message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diffOK = new javax.swing.JButton();
        diffNoShow = new javax.swing.JCheckBox();
        diffScroll = new javax.swing.JScrollPane();
        diffMessage = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        diffOK.setText("OK");
        diffOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diffOKActionPerformed(evt);
            }
        });

        diffNoShow.setText("Do not show this again.");
        diffNoShow.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                diffNoShowStateChanged(evt);
            }
        });

        diffScroll.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        diffScroll.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Checked Values Removed", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        diffScroll.setPreferredSize(new java.awt.Dimension(272, 122));

        diffMessage.setEditable(false);
        diffMessage.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        diffMessage.setColumns(20);
        diffMessage.setLineWrap(true);
        diffMessage.setRows(5);
        diffMessage.setWrapStyleWord(true);
        diffMessage.setBorder(null);
        diffScroll.setViewportView(diffMessage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(diffScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(diffNoShow)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(diffOK)))
                .addGap(135, 135, 135))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(diffScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(diffNoShow)
                .addGap(18, 18, 18)
                .addComponent(diffOK)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diffOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diffOKActionPerformed
        this.dispose();
    }//GEN-LAST:event_diffOKActionPerformed

    private void diffNoShowStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_diffNoShowStateChanged
        MainForm.diffShow = !diffNoShow.isSelected();
    }//GEN-LAST:event_diffNoShowStateChanged

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea diffMessage;
    private javax.swing.JCheckBox diffNoShow;
    private javax.swing.JButton diffOK;
    private javax.swing.JScrollPane diffScroll;
    // End of variables declaration//GEN-END:variables
}
