/**
 * Licensed to Apereo under one or more contributor license
 * agreements. See the NOTICE file distributed with this work
 * for additional information regarding copyright ownership.
 * Apereo licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a
 * copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
/*
 * RandomSelectDialog.java
 *
 * Created on February 5, 2007, 1:03 PM
 */

package scripteditor;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
/**
 *
 * @author  Moz123
 */
public class RandomSelectDialog extends javax.swing.JDialog {

    private String mTaxaLevel; // Taxa Level
    private int mNumberTaxa; // Number of taxa to use
   // private int mNumberImages; // number of Images per Taxa
    private boolean mCommonNames; // use Common Names when true
    private int mResult; // Return result for Continue and Cancel buttons
    private int mMode; // Study Quiz or Test modes study = 1, quiz =  2 and test = 3



    /** Creates new form RandomSelectDialog */
    public RandomSelectDialog(String taxaLevel, boolean commonNames, int numTaxa) {
        initComponents();
        addEscapeListener(this);
        Image image = null;
        try
        {
            image = ImageIO.read(new File(Configuration.ApplicationPath()+"/Graphics/icon.jpg"));
        }
        catch(IOException ex)
        {
            Logger.getLogger(Search_table.class.getName()).log(Level.SEVERE, null, ex);
        }
        setIconImage(image);
       bgButtonGroup.add(this.jRadioButton1);
       bgButtonGroup.add(this.jRadioButton2);
       bgButtonGroup.add(this.jRadioButton3);
       bgButtonGroup.add(this.jRadioButton4);
       jRadioButton4.setSelected(true);
       mTaxaLevel = taxaLevel;
       mCommonNames = commonNames;
       mNumberTaxa = numTaxa;
       chkCommonNames.setSelected(commonNames);
       if(taxaLevel != null){
       if(taxaLevel.compareTo("Family") == 0)
       dropTaxaLevel.setSelectedIndex(2);
       if(taxaLevel.compareTo("Genus") == 0)
       dropTaxaLevel.setSelectedIndex(3);
       if(taxaLevel.compareTo("Species") == 0)
       dropTaxaLevel.setSelectedIndex(4);
       if(taxaLevel.compareTo("Common Name") == 0)
       dropTaxaLevel.setSelectedIndex(4);
       }

       dropNumberTaxa.setSelectedIndex(numTaxa - 1);
    }

    public static void addEscapeListener(final JDialog dialog)
    {
        ActionListener escListner = new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                dialog.setVisible(false);
            }
        };
        dialog.getRootPane().registerKeyboardAction(escListner,
                KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE,0),
                JComponent.WHEN_IN_FOCUSED_WINDOW);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dropTaxaLevel = new javax.swing.JComboBox();
        dropNumberTaxa = new javax.swing.JComboBox();
        chkCommonNames = new javax.swing.JCheckBox();
        btContinue = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        btCancel = new javax.swing.JButton();

        setTitle("Taxa Selection");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Random Taxa Selection", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel1.setText("Taxonomic Level:");

        jLabel2.setText("Number of Taxa:");

        dropTaxaLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Taxonomic Level", "------------------------", "Family", "Genus", "Species" }));
        dropTaxaLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropTaxaLevelActionPerformed(evt);
            }
        });

        dropNumberTaxa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        chkCommonNames.setText("Use Common Names");
        chkCommonNames.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkCommonNames.setEnabled(false);
        chkCommonNames.setMargin(new java.awt.Insets(0, 0, 0, 0));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 28, Short.MAX_VALUE)
                                .add(dropTaxaLevel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 155, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                .add(jLabel2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 120, Short.MAX_VALUE)
                                .add(dropNumberTaxa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 68, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(chkCommonNames)
                        .add(73, 73, 73))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(dropTaxaLevel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(15, 15, 15)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(dropNumberTaxa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(24, 24, 24)
                .add(chkCommonNames)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btContinue.setText("Continue");
        btContinue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btContinueMouseReleased(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quick Launch", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jRadioButton1.setText("Study Images");
        jRadioButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jRadioButton2.setText("Take a Quiz");
        jRadioButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jRadioButton3.setText("Take a Test");
        jRadioButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton3.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jRadioButton4.setText("Back to Main Screen");
        jRadioButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton4.setMargin(new java.awt.Insets(0, 0, 0, 0));

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(23, 23, 23)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jRadioButton4)
                    .add(jRadioButton2))
                .add(42, 42, 42)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jRadioButton1)
                    .add(jRadioButton3))
                .add(12, 12, 12))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jRadioButton4)
                    .add(jRadioButton1))
                .add(21, 21, 21)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jRadioButton3)
                    .add(jRadioButton2))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btCancel.setText("Cancel");
        btCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btCancelMouseReleased(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(btContinue)
                        .add(49, 49, 49)
                        .add(btCancel)
                        .add(58, 58, 58))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        layout.linkSize(new java.awt.Component[] {btCancel, btContinue}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(14, 14, 14)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btContinue)
                    .add(btCancel))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dropTaxaLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropTaxaLevelActionPerformed

        if(dropTaxaLevel.getSelectedIndex() == 4){
            chkCommonNames.setEnabled(true);
        }
        else
            chkCommonNames.setEnabled(false);
    }//GEN-LAST:event_dropTaxaLevelActionPerformed

    private void btCancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCancelMouseReleased
        mResult = 0;
        this.hide();
    }//GEN-LAST:event_btCancelMouseReleased



    private void btContinueMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btContinueMouseReleased
        if(this.dropTaxaLevel.getSelectedIndex() < 2){
            Utilities.MessageDialog(this, "Please select a taxonomic level");
            //JOptionPane.showMessageDialog(this, "Please select a taxonomic level", "No Taxonomic Level Selected", JOptionPane.OK_OPTION);
            return;
        }
        else{


            mTaxaLevel = this.dropTaxaLevel.getSelectedItem().toString();
            if(mTaxaLevel.compareTo("Species") == 0 && chkCommonNames.isSelected() == true){
                mTaxaLevel = "Common Name";
            }



            mNumberTaxa = this.dropNumberTaxa.getSelectedIndex() + 1;
          //  mNumberImages = this.dropNumberImages.getSelectedIndex() + 1;
            mCommonNames = this.chkCommonNames.isSelected();
            mResult = 1; // means continue button was pressed;
            if(jRadioButton1.isSelected()){
                mMode = 1;
            }
            else if(jRadioButton2.isSelected()){
                mMode = 2;
            }
            else if(jRadioButton3.isSelected()){
                mMode = 3;
            }
//            else{
//                JOptionPane.showMessageDialog(this, "Random taxa has been selected.");
//            }
            this.setVisible(false);
        }
    }//GEN-LAST:event_btContinueMouseReleased

    public String getTaxaLevel(){
        return mTaxaLevel;
    }

  //  public int getImageCount(){
  //      return mNumberImages;
  //  }

    public int getTaxaCount(){
        return mNumberTaxa;
    }

    public boolean getUseCommonNames(){
        return mCommonNames;
    }

    public int getResults(){
        return mResult;
    }

    public int getMode(){
        return mMode;
    }

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgButtonGroup;
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btContinue;
    private javax.swing.JCheckBox chkCommonNames;
    private javax.swing.JComboBox dropNumberTaxa;
    private javax.swing.JComboBox dropTaxaLevel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables

}
