/**
 * Licensed to Apereo under one or more contributor license
 * agreements. See the NOTICE file distributed with this work
 * for additional information regarding copyright ownership.
 * Apereo licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a
 * copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SearchRes.java
 *
 * Created on Jan 23, 2012, 2:51:48 PM
 */
package scripteditor;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Preethy
 */
public class SearchRes extends javax.swing.JDialog {
private String[] StudySet;
String[] prev;
String[] study;
private String[] Items;
private String[] Items2;
boolean add=false;
String levl;
boolean bt1=false;
boolean bt2=false;
MainForm mainF;
Search_table prj;
String searchLevel;
String level;
boolean exist=false;
public boolean taxanull=false;
    /** Creates new form SearchRes */
    public SearchRes(String[] PrevTaxa,String taxal) {
         }

  SearchRes(MainForm obj,Search_table obj2,String Srchlevel,String level,boolean exist)  {
      initComponents();
        Image image=null;
        try {
            image=ImageIO.read(new File(Configuration.ApplicationPath() + "/Graphics/icon.jpg"));
          //  image=ImageIO.read(new File(Configuration.UserPath() + "/Graphics/icon.jpg"));
        } catch (IOException ex) {
            Logger.getLogger(SearchRes.class.getName()).log(Level.SEVERE, null, ex);
        }
         setIconImage(image);
      this.mainF = obj;
      this.prj=obj2;
      this.searchLevel=Srchlevel;
      this.level=level;
      this.exist=exist;

       // throw new UnsupportedOperationException("Not yt eimplemented");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list1 = new java.awt.List();
        list2 = new java.awt.List();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Selected Taxa");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        list2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list2ActionPerformed(evt);
            }
        });

        jButton1.setText("Add Selected taxa to Study Set");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clear  the Current set Add new Taxa");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Return to Search Screen");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton3MouseReleased(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Currently selected taxa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(list2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
                        .addGap(81, 81, 81))))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1)
                .addContainerGap(218, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(list2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void list2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        // TODO add your handling code here:
        bt1=true;

        mainF.mTaxa =null;
        mainF.taxonomicLevel=searchLevel;


        if(Items2!=null){
           mainF.mTaxa=Items2;
        }
        //else{ //Commented by preethy on 19-06-2012
      //  mainF.mTaxa=Items;
       // }

        mainF.group=false;
        this.setVisible(false);
        prj.setVisible(false);
    }//GEN-LAST:event_jButton2MouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton3MousePressed

    private void jButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseReleased
        // TODO add your handling code here:
        this.setVisible(false);

}//GEN-LAST:event_jButton3MouseReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if(mainF.mTaxa==null || mainF.mTaxa.length==0)
        {
           list2.add("No taxa are currently selected.");

           jButton2.setEnabled(false);
        }
        else
        {
        for(int i=0;i<StudySet.length;i++){
           list2.add(StudySet[i]);
        }
        }

    }//GEN-LAST:event_formWindowOpened

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        // TODO add your handling code here
        if(mainF.mTaxa!=null){
       if(level.equals("Family"))
          {
              Utilities.MessageDialog(this, "We are sorry; you cannot add the selected taxa to the study set\n because the current study set consists of families and the selected \n taxa are at the " +searchLevel+ " level. Please select a different option.");
          }else if((!searchLevel.equalsIgnoreCase(level)) && (level.equals("Common Name") ) ){
              Utilities.MessageDialog(this, "We are sorry; you cannot add the selected taxa to the study set because\n the current study set consists of species (selected by common name) and\n the selected taxa are at the generic level. Please select a different option.");
          }else if((!searchLevel.equalsIgnoreCase(level)) && (level.equals("Genus") ) ){
              Utilities.MessageDialog(this, "We are sorry; you cannot add the selected taxa to the study set\n because the current study set consists of genera and the selected \n taxa are at the species level. Please select a different option.");
          }else if((!searchLevel.equalsIgnoreCase(level)) && (level.equals("Species")) && (searchLevel.equals("Genus")) ){
              Utilities.MessageDialog(this, "We are sorry; you cannot add the selected taxa to the study set\n because the current study set consists of species selected by \n their scientific names, and the selected taxa are at the genus level.\n Please select a different option.");
          }else if((!searchLevel.equalsIgnoreCase(level)) && (level.equals("Species")) && (searchLevel.equals("Common Name")) ){
              Utilities.MessageDialog(this, "We are sorry; you cannot add the selected taxa to the study because the current \nstudy set consists of species selected by their scientific names, and the selected taxa \nare at the species level, selected by common name. Please select a different option.");
          }else if(exist){
              Utilities.MessageDialog(this, "We are sorry; you cannot add the selected taxa to the study set\n because these taxa are already selected.");
          }
      else
       {
          mainF.group=false;
        bt1=true;
       int k=mainF.mTaxa.length;


        String [] mainItems = mainF.mTaxa;
        String [] temp = new String[k+Items.length];
       for(int i=0;i<mainItems.length;i++)
        {

           temp[i] = mainItems[i];
        }
        for(int i=0;i<Items.length;i++)
        {
            temp[k]=Items[i];
            k++;
        }
        mainF.mTaxa = temp;

        this.setVisible(false);
        prj.setVisible(false);
       }
    }else{
             mainF.mTaxa =null;
             mainF.taxonomicLevel=searchLevel;
             mainF.mTaxa=Items;
             mainF.taxanull=true;
             mainF.group=false;
             this.setVisible(false);
             prj.setVisible(false);

        }

    }//GEN-LAST:event_jButton1MouseReleased
    public void taxasel(String[] PrevTaxa,String taxal){
      levl=taxal;
       String tx="ts";
       if(taxal.equals("Family")||(taxal.equals("Genus"))||(taxal.equals("Species")))
        {
          for(int i=0;i<PrevTaxa.length;i++)   {
               prev=PrevTaxa;
               setItems(prev);
               list2.add(prev[i]);
              this.setVisible(true);
            }
         }
  }
 public void currentSet( String[] New) {
     try{
         for(int i=0;i<New.length;i++){
               setStudySet(New);
         }
       }catch(Exception e){}
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private java.awt.List list1;
    private java.awt.List list2;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the StudySet
     */
    public String[] getStudySet() {
        return StudySet;
    }

    /**
     * @param Items the Items to set
     */
    public void setItems(String[] Items) {
        this.Items = Items;
    }
public void setItems2(String[] Items) {
        this.Items2 = Items;
    }
    /**
     * @param StudySet the StudySet to set
     */
    public void setStudySet(String[] StudySet) {
        this.StudySet = StudySet;
    }
}
